"""initial schema

Revision ID: be5d72592b09
Revises: 
Create Date: 2026-08-05 21:19:54.426104+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'be5d72592b09'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code_iso2', sa.String(length=2), nullable=False),
    sa.Column('code_iso3', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_local', sa.String(length=120), nullable=True),
    sa.Column('admission_platform_name', sa.String(length=120), nullable=True),
    sa.Column('admission_platform_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('academic_year_format', sa.String(length=20), nullable=True),
    sa.Column('scraping_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scraping_frequency', sa.Enum('daily', 'weekly', 'monthly', 'seasonal', name='scraping_frequency'), server_default='seasonal', nullable=False),
    sa.Column('last_scrape_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(code_iso2) = 2', name=op.f('ck_countries_code_iso2_length')),
    sa.CheckConstraint('char_length(code_iso3) = 3', name=op.f('ck_countries_code_iso3_length')),
    sa.CheckConstraint('char_length(language) = 2', name=op.f('ck_countries_language_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('code_iso2', name=op.f('uq_countries_code_iso2')),
    sa.UniqueConstraint('code_iso3', name=op.f('uq_countries_code_iso3'))
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='scrape_status'), server_default='running', nullable=False),
    sa.Column('records_scraped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_inserted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_scrape_runs_finished_after_started')),
    sa.CheckConstraint('records_failed >= 0', name=op.f('ck_scrape_runs_records_failed_non_negative')),
    sa.CheckConstraint('records_inserted >= 0', name=op.f('ck_scrape_runs_records_inserted_non_negative')),
    sa.CheckConstraint('records_scraped >= 0', name=op.f('ck_scrape_runs_records_scraped_non_negative')),
    sa.CheckConstraint('records_updated >= 0', name=op.f('ck_scrape_runs_records_updated_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index(op.f('ix_scrape_runs_country_code'), 'scrape_runs', ['country_code'], unique=False)
    op.create_index('ix_scrape_runs_platform_started_at', 'scrape_runs', ['platform', 'started_at'], unique=False)
    op.create_table('oumno_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('preferred_language', sa.String(length=2), server_default='fr', nullable=False),
    sa.Column('education_level', sa.Enum('high_school', 'bachelor', 'master', name='education_level'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(preferred_language) = 2', name=op.f('ck_oumno_users_preferred_language_length')),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code_iso2'], name=op.f('fk_oumno_users_country_code_countries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oumno_users')),
    sa.UniqueConstraint('email', name=op.f('uq_oumno_users_email'))
    )
    op.create_index(op.f('ix_oumno_users_country_code'), 'oumno_users', ['country_code'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_local', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.Enum('public', 'private', 'semi_public', name='university_type'), nullable=True),
    sa.Column('accreditation_body', sa.String(length=200), nullable=True),
    sa.Column('founding_year', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('international_student_count', sa.Integer(), nullable=True),
    sa.Column('oumno_partner', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('founding_year IS NULL OR founding_year BETWEEN 800 AND 2200', name=op.f('ck_universities_founding_year_plausible')),
    sa.CheckConstraint('international_student_count IS NULL OR international_student_count >= 0', name=op.f('ck_universities_international_student_count_non_negative')),
    sa.CheckConstraint('international_student_count IS NULL OR student_count IS NULL OR international_student_count <= student_count', name=op.f('ck_universities_international_students_within_total')),
    sa.CheckConstraint('student_count IS NULL OR student_count >= 0', name=op.f('ck_universities_student_count_non_negative')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_universities_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universities')),
    sa.UniqueConstraint('country_id', 'external_id', name=op.f('uq_universities_country_id_external_id'))
    )
    op.create_index('ix_universities_country_id_name', 'universities', ['country_id', 'name'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('source_key', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_local', sa.String(length=500), nullable=False),
    sa.Column('degree_level', sa.Enum('bachelor', 'master', 'doctorate', 'other', name='degree_level'), server_default='other', nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('field_code', sa.String(length=50), nullable=True),
    sa.Column('language_of_instruction', sa.ARRAY(sa.String(length=2)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('duration_years', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('duration_semesters', sa.Integer(), nullable=True),
    sa.Column('tuition_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('application_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('application_open_date', sa.Date(), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('is_international_program', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_visa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('application_fee IS NULL OR application_fee >= 0', name=op.f('ck_programs_application_fee_non_negative')),
    sa.CheckConstraint('application_open_date IS NULL OR application_deadline IS NULL OR application_open_date <= application_deadline', name=op.f('ck_programs_application_window_ordered')),
    sa.CheckConstraint('capacity IS NULL OR capacity >= 0', name=op.f('ck_programs_capacity_non_negative')),
    sa.CheckConstraint('duration_semesters IS NULL OR duration_semesters > 0', name=op.f('ck_programs_duration_semesters_positive')),
    sa.CheckConstraint('duration_years IS NULL OR duration_years > 0', name=op.f('ck_programs_duration_years_positive')),
    sa.CheckConstraint('tuition_fee IS NULL OR currency IS NOT NULL', name=op.f('ck_programs_fee_requires_currency')),
    sa.CheckConstraint('tuition_fee IS NULL OR tuition_fee >= 0', name=op.f('ck_programs_tuition_fee_non_negative')),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_programs_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs')),
    sa.UniqueConstraint('university_id', 'source_key', 'academic_year', name=op.f('uq_programs_university_id_source_key_academic_year'))
    )
    op.create_index('ix_programs_degree_level_field_of_study', 'programs', ['degree_level', 'field_of_study'], unique=False)
    op.create_index('ix_programs_source_platform_academic_year', 'programs', ['source_platform', 'academic_year'], unique=False)
    op.create_table('admission_criteria',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('criterion_type', sa.Enum('grade', 'test', 'interview', 'portfolio', 'essay', 'letters_of_recommendation', 'language_test', 'extracurricular', 'other', name='criterion_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('minimum_score', sa.String(length=50), nullable=True),
    sa.Column('maximum_score', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight IS NULL OR (weight >= 0 AND weight <= 1)', name=op.f('ck_admission_criteria_weight_is_a_ratio')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_admission_criteria_program_id_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_criteria'))
    )
    op.create_index(op.f('ix_admission_criteria_program_id'), 'admission_criteria', ['program_id'], unique=False)
    op.create_table('admission_statistics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('applicants_count', sa.Integer(), nullable=True),
    sa.Column('admitted_count', sa.Integer(), nullable=True),
    sa.Column('waitlist_count', sa.Integer(), nullable=True),
    sa.Column('rejected_count', sa.Integer(), nullable=True),
    sa.Column('min_score_admitted', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score_admitted', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_score_admitted', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('acceptance_rate IS NULL OR (acceptance_rate >= 0 AND acceptance_rate <= 1)', name=op.f('ck_admission_statistics_acceptance_rate_is_a_ratio')),
    sa.CheckConstraint('admitted_count IS NULL OR admitted_count >= 0', name=op.f('ck_admission_statistics_admitted_count_non_negative')),
    sa.CheckConstraint('admitted_count IS NULL OR applicants_count IS NULL OR admitted_count <= applicants_count', name=op.f('ck_admission_statistics_admitted_within_applicants')),
    sa.CheckConstraint('applicants_count IS NULL OR applicants_count >= 0', name=op.f('ck_admission_statistics_applicants_count_non_negative')),
    sa.CheckConstraint('min_score_admitted IS NULL OR max_score_admitted IS NULL OR min_score_admitted <= max_score_admitted', name=op.f('ck_admission_statistics_score_range_ordered')),
    sa.CheckConstraint('rejected_count IS NULL OR rejected_count >= 0', name=op.f('ck_admission_statistics_rejected_count_non_negative')),
    sa.CheckConstraint('waitlist_count IS NULL OR waitlist_count >= 0', name=op.f('ck_admission_statistics_waitlist_count_non_negative')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_admission_statistics_program_id_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_statistics')),
    sa.UniqueConstraint('program_id', 'academic_year', name=op.f('uq_admission_statistics_program_id_academic_year'))
    )
    op.create_table('oumno_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'accepted', 'rejected', 'waitlisted', name='application_status'), server_default='draft', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'draft' OR submitted_at IS NOT NULL", name=op.f('ck_oumno_applications_submitted_at_set_once_left_draft')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_oumno_applications_program_id_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['oumno_users.id'], name=op.f('fk_oumno_applications_user_id_oumno_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oumno_applications')),
    sa.UniqueConstraint('user_id', 'program_id', name=op.f('uq_oumno_applications_user_id_program_id'))
    )
    op.create_index(op.f('ix_oumno_applications_program_id'), 'oumno_applications', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oumno_applications_program_id'), table_name='oumno_applications')
    op.drop_table('oumno_applications')
    op.drop_table('admission_statistics')
    op.drop_index(op.f('ix_admission_criteria_program_id'), table_name='admission_criteria')
    op.drop_table('admission_criteria')
    op.drop_index('ix_programs_source_platform_academic_year', table_name='programs')
    op.drop_index('ix_programs_degree_level_field_of_study', table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_universities_country_id_name', table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_oumno_users_country_code'), table_name='oumno_users')
    op.drop_table('oumno_users')
    op.drop_index('ix_scrape_runs_platform_started_at', table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_country_code'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_table('countries')
    # ### end Alembic commands ###

    # Autogenerate does not clean up native enum types: dropping a table leaves
    # the types its columns referenced behind, so re-applying this migration
    # fails with "type ... already exists" and a rollback cannot be undone.
    for enum_name in (
        'application_status',
        'education_level',
        'scrape_status',
        'criterion_type',
        'degree_level',
        'university_type',
        'scraping_frequency',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
